import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";
import ExcerciseProvider from "@/Context/ExcerciseProvider";
import { ToastContainer } from "react-toastify/unstyled";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const geist = Geist({
    variable: "--font-geist",
    subsets: ["latin"],
});
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      
      
      className={`${geistSans.variable} ${geistMono.variable} ${geist.variable} dark  h-full antialiased`}
    >
     
      <body className="  text-black dark:bg-gray-950 dark:text-white bg-white min-h-full flex flex-col">
        
        
        <ExcerciseProvider>
             <Navbar />
               {children}
                <ToastContainer />
        </ExcerciseProvider>
        


      </body>
    </html>
  );
}
