import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";
import ExcerciseProvider from "@/Context/ExcerciseProvider";
import "./globals.css";
import Footer from "@/Component/Footer";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
   variable: "--font-oswald", 
   subsets: ["latin"], });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      
      className={`${oswald.variable}  dark  h-full  antialiased`}
    >
     
      <body className=" text-black dark:bg-gray-950 dark:text-white bg-white w-full min-h-screen m-0 p-0 ">
        
        
        <ExcerciseProvider>
             <Navbar />
               {children}
             <Footer></Footer>
           <ToastContainer />  
              
        </ExcerciseProvider>
        

      </body>
    </html>
  );
}
