import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";
import ExcerciseProvider from "@/Context/ExcerciseProvider";
import { ToastContainer } from "react-toastify/unstyled";

import "./globals.css";
import Footer from "@/Component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      
      className={`${geistSans.variable} ${geistMono.variable}  dark w-full h-full antialiased`}
    >
     
      <body className="text-black dark:bg-gray-950 dark:text-white bg-white w-full min-h-full m-0 p-0 flex flex-col">
        
        
        <ExcerciseProvider>
             <Navbar />
               {children}
             <Footer></Footer>
        </ExcerciseProvider>
        


      </body>
    </html>
  );
}
